"""Initial schema for flights, airports, airlines, aircraft, and weather

Revision ID: 88afd7a82949
Revises: 
Create Date: 2026-03-15 12:57:05.799740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88afd7a82949'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('iata_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_index(op.f('ix_airlines_iata_code'), 'airlines', ['iata_code'], unique=False)
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('congestion_index', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airports_icao_code'), 'airports', ['icao_code'], unique=True)
    op.create_table('aircraft',
    sa.Column('tail_number', sa.String(length=20), nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('maintenance_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airline_iata'], ['airlines.iata_code'], ),
    sa.PrimaryKeyConstraint('tail_number')
    )
    op.create_index(op.f('ix_aircraft_tail_number'), 'aircraft', ['tail_number'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=False),
    sa.Column('aircraft_tail', sa.String(length=20), nullable=True),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delay_probability', sa.Float(), nullable=True),
    sa.Column('expected_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('ml_explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_tail'], ['aircraft.tail_number'], ),
    sa.ForeignKeyConstraint(['airline_iata'], ['airlines.iata_code'], ),
    sa.ForeignKeyConstraint(['destination_iata'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_iata'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_arrival'), 'flights', ['scheduled_arrival'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_departure'), 'flights', ['scheduled_departure'], unique=False)
    op.create_table('weather_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_iata', sa.String(length=3), nullable=False),
    sa.Column('flight_id', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airport_iata'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_events_airport_iata'), 'weather_events', ['airport_iata'], unique=False)
    op.create_index(op.f('ix_weather_events_timestamp'), 'weather_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_events_timestamp'), table_name='weather_events')
    op.drop_index(op.f('ix_weather_events_airport_iata'), table_name='weather_events')
    op.drop_table('weather_events')
    op.drop_index(op.f('ix_flights_scheduled_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_scheduled_arrival'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_aircraft_tail_number'), table_name='aircraft')
    op.drop_table('aircraft')
    op.drop_index(op.f('ix_airports_icao_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_iata_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
